backend:
  name: "github"
  repo: "decoy-school/decoy-school-2"

media_folder: static/assets

collections:
  - name: pages
    label: pages
    folder: src/pages
    create: false
    slug: {{slug}}
    fields: 
      - {name: path, widget: hidden}
      - {name: title, label: Title, widget: string}
      - {name: navTitle, widget: hidden}
      - {name: order, widget: hidden}
      - {name: "toc", label: Table of Contents, widget: boolean, default: false}
      - {name: template, widget: hidden}
      - {name: body, label: Body, widget: markdown}
    editor:
      preview: true
  
path: "/"
title: Welcome
navTitle: "Home"
order: 1
toc: false
template: "indexTemplate"